import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import ClientComponent from "./clientComponent";
import "@/styles/main.scss";

const robotoCondensed = Roboto_Condensed({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Anni Haus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoCondensed.className}>
        <ClientComponent>{children}</ClientComponent>
      </body>
    </html>
  );
}
